services:
  mysql:
    image: mysql:8.0
    container_name: fintrack_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fintrack_db
      MYSQL_USER: fintrack_user
      MYSQL_PASSWORD: Fintrack@12345
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: fintrack_backend
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "True"
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      JWT_SECRET_KEY: docker-dev-secret
      DB_HOST: mysql
      DB_USER: fintrack_user
      DB_PASSWORD: Fintrack@12345
      DB_NAME: fintrack_db
      DB_PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: